### ISSUE TITLE
ZeroNetX enhanced branch: deleting site error: FileNotFoundError: [Errno 2] No such file or directory: data/users/*/content.json

### ISSUE THREAD

**Issue by slrslr** [ZeroNetX/ZeroNet#126]
After trying to delete site, it seems the site was deleted yet the log shows:

```
[11:47:41] Site:1JjXZn..kG4m DbQuery error: OperationalError: near "&": syntax error in UiWebsocket.py line 683 > SiteStorage.py line 258 > 248 > Db.py line 150 > DbCursor.py line 107

[11:51:04] - Unhandled exception: FileNotFoundError: [Errno 2] No such file or directory: './data/1JjXZnEKKm7sLpFj3J7DiSRBLnjMVkkG4m/data/users/1HGiNSHwxEMyh5XPP22V3PFAK6RXHkQKq8/content.json' in <gevent>/threadpool.py line 167 > SiteStorage.py line 391 > 277
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gevent/threadpool.py", line 167, in __run_task
    thread_result.set(func(*args, **kwargs))
  File "/home/user/zeronet/src/Site/SiteStorage.py", line 391, in loadJson
    with self.open(inner_path, "r", encoding="utf8") as file:
  File "/home/user/apps/zeronet/src/Site/SiteStorage.py", line 277, in open
    return open(file_path, mode, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: './data/1JjXZnEKKm7sLpFj3J7DiSRBLnjMVkkG4m/data/users/1HGiNSHwxEMyh5XPP22V3PFAK6RXHkQKq8/content.json'
```

**Comment by canewsin** [comment]
ZeroNet Enhanced Branch ?

**Comment by slrslr** [comment]
if i was not wrong (i could be), then yes

**Comment by canewsin** [comment]
I pushed changes to ZE try now and report

**Comment by slrslr** [comment]
if i did everything right, it seems error is gone, site was deleted without error 👍
