### ISSUE TITLE
ZeroNetX enhanced branch: Unhandled exception: KeyError: content.json:1641509623' in <gevent>/greenlet.py line 906 > FileRequest.py line 173

### ISSUE THREAD

**Issue by slrslr** [ZeroNetX/ZeroNet#127]
In recent Zeronet enhanced branch i have seen:

```
Unhandled exception: KeyError: '1HMLvnRWViMnuvZc5LK4Dm86sZNcSH1jdh/data/users/1AmeB7f5wBfJm6iR7MRZfFh65xkJzaVCX7/content.json:1641509623' in <gevent>/greenlet.py line 906 > FileRequest.py line 173
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/user/zeronet/src/File/FileRequest.py", line 173, in downloader
    del self.server.files_parsing[file_uri]
KeyError: '1HMLvnRWViMnuvZc5LK4Dm86sZNcSH1jdh/data/users/1AmeB7f5wBfJm6iR7MRZfFh65xkJzaVCX7/content.json:1641509623'
```

also following error, yet it may related to site issue not ZN:

```
23:47:51] Site:1HELLo..Ri9d 1UkrrSpnJmuiig6r5v88Kn3isaR64Fbh3 feed query Topics error: KeyError: 'body' in NewsfeedPlugin.py line 148
[23:47:57] Site:1HELLo..Ri9d 1UkrrSpnJmuiig6r5v88Kn3isaR64Fbh3 feed query Topics error: KeyError: 'body' in NewsfeedPlugin.py line 148
[23:48:36] Site:1UkrrS..Fbh3 DbQuery error: OperationalError: no such column: magnets.dl in UiWebsocket.py line 683 > SiteStorage.py line 258 > 248 > Db.py line 150 > DbCursor.py line 107
```

**Comment by slrslr** [comment]
I do not see most of these errors anymore (only that site related "OperationalError") which is not possibly issue of ZN.
