### ISSUE TITLE
int arm64 proot ubuntu zeronet not work

### ISSUE THREAD

**Issue by WangHHY19931001** [ZeroNetX/ZeroNet#140]
version: zeronet-src v 0.7.6 (4565)
os: 
cat /etc/issue
Ubuntu 20.04.3 LTS \n \
uname -a
Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Wed Dec 15 19:57:07 CST 2021 aarch64 aarch64 aarch64 GNU/Linux
report:
python3 zeronet.py 
- Starting ZeroNet...
[07:22:43] - Unhandled exception: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "zeronet.py", line 16, in main
    import main
  File "/root/ZeroNet/src/main.py", line 74, in <module>
    from Plugin import PluginManager
  File "/root/ZeroNet/src/Plugin/PluginManager.py", line 211, in <module>
    plugin_manager = PluginManager()  # Singletone
  File "/root/ZeroNet/src/Plugin/PluginManager.py", line 19, in __init__
    self.path_plugins = os.path.abspath(os.path.dirname(plugins.__file__))
  File "/usr/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
---
Please report it: https://github.com/HelloZeroNet/ZeroNet/issues/new?assignees=&labels=&template=bug-report.md

**Comment by canewsin** [comment]
Clonning Repo requires `--recursive` param due to submodules.
try
> git submodule init && git submodules update

**Comment by slrslr** [comment]
> git submodule update

**Comment by WangHHY19931001** [comment]
done it work
