### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by nerd36** [ZeroNetX/ZeroNet#155]
### Step 1: Please describe your environment

  * ZeroNet version: 69d7eac
  * Operating system: Arch Linux
  * Tor status: always
  * Opened port: yes

### Step 2: Describe the problem:

```
$ python3 ./start.py
- Starting ZeroNet...
[04:31:54] - Unhandled exception: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/m/Downloads/New_Folder/ZeroNet/ZeroNetX/ZeroNet/zeronet.py", line 16, in main
    import main
  File "/home/m/Downloads/New_Folder/ZeroNet/ZeroNetX/ZeroNet/src/main.py", line 74, in <module>
    from Plugin import PluginManager
  File "/home/m/Downloads/New_Folder/ZeroNet/ZeroNetX/ZeroNet/src/Plugin/PluginManager.py", line 211, in <module>
    plugin_manager = PluginManager()  # Singletone
  File "/home/m/Downloads/New_Folder/ZeroNet/ZeroNetX/ZeroNet/src/Plugin/PluginManager.py", line 19, in __init__
    self.path_plugins = os.path.abspath(os.path.dirname(plugins.__file__))
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
---
```

**Comment by nerd36** [comment]
I had to use `git clone --recursive`
