### ISSUE TITLE
No peers on Dasboard, unable to use ZNX and "division by zero in <gevent>/greenlet.py line 908 > FileServer.py line 341"

### ISSUE THREAD

**Issue by slrslr** [ZeroNetX/ZeroNet#210]
### Step 1: Please describe your environment

\# lsb_release -d;python3 --version;./ZeroNet.sh --version

Description:    Debian GNU/Linux 11 (bullseye)
Python 3.9.2
Version: 0.8.5 r4625

### Step 2: Describe the problem:

I was trying to start ZN and seeing no peers on dashboard zite, no trackers. Clicking Config link it says:
"1 configuration item value changed" which is:

> Trackers
> Discover new peers using these adresses

It is empty. Even i did nothing since ZN start.

Screenshot:
![webp image](https://i.postimg.cc/y8btcqXs/znx-trackers.webp)
https://i.postimg.cc/y8btcqXs/znx-trackers.webp

My zeronet.conf:

```
[global]
threads_fs_write = 4
threads_fs_read = 4
fileserver_port = 32633
ui_ip = *
ui_port = 80
#multiuser_local
optional_limit = 90%
autodownload_bigfile_size_limit = 200
bigfile_size_limit = 1000
```

So i have manually inserted some trackers into that Trackers text area in /Config:

> zero://boot3rdez4rzn36x.onion:15441
> udp://tracker.coppersurfer.tk:6969
> udp://104.238.198.186:8000
> udp://retracker.akado-ural.ru:80
> http://h4.trakx.nibba.trade:80/announce
> http://open.acgnxtracker.com:80/announce
> http://tracker.bt4g.com:2095/announce

saved and went to command line to exit and start, yet seen this:

> [07:35:52] - Unhandled exception: ZeroDivisionError: division by zero in <gevent>/greenlet.py line 908 > FileServer.py line 341
> Traceback (most recent call last):
>   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
>   File "/root/zeronetx/core/src/File/FileServer.py", line 341, in announceSites
>     sleep = max(0, 60 * 20 / len(config.trackers) - taken)
> ZeroDivisionError: division by zero

After next start, ZNX dashboard site still not connects:

> Trackers announcing: 0, error: 6, done: 1
> Tracker connection error detected.

[debug.log here](https://bin.disroot.org/?8b984486f7dc9759#8awER2bGa6NvvimQmpoPYg1mRHzKccbqRDcF9k5ZHMwz) please

Fix this please and let me know if some detail or test is needed.

**Comment by slrslr** [comment]
UPDATE: the trackers i have tried to add as a workaround all failed per the log (not sure about acgn* one), but after i have added other trackers from my working ZN instance, it loaded main dashboard site and obtained additional working trackers & peers, so the tracker issue can be fixed by @canewsin by adding some working "bootstrap" trackers i guess, maybe automating it from https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt (remove empty lines) ?

**Comment by slrslr** [comment]
Maybe even set mentioned Ngosang trackers URL as a source for new trackers (Zeronet will obtain these like if it is a Zeronet trackers file that is being produced by for example [Syncronite](http://127.0.0.1:43110/15CEFKBRHFfAP9rmL6hhLmHoXrrgmw4B5o/) ). Syncronite is automatically updated daily and it is ran by at least 2 people so it can be said it is decentralized source of a new trackers (to connect it one still needs trackers - obtained thanks to you to build Ngosang list URL into Zeronet as a trackers resource.
